version: "3.7"
services:
  server:
    build: server
    image: localhost:5001/ohad-airports-finder-server
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - DEBUG=true
  client:
    build: client
    image: localhost:5001/ohad-airports-finder-client
    ports:
      - "3000:3000"
