apiVersion: v1
kind: Service
metadata:
  labels:
    app: ohad-airports-finder-client-service
  name: ohad-airports-finder-client-service
spec:
  type: LoadBalancer
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
  selector:
    app: ohad-airports-finder-client-service
status:
  loadBalancer: {}
