apiVersion: apps/v1
kind: Deployment
metadata:
  name: ohad-airports-finder-server-deployment
  labels:
      app: ohad-airports-finder-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ohad-airports-finder-server
  template:
    metadata:
      labels:
        app: ohad-airports-finder-server
    spec:
      containers:
      - name: ohad-airports-finder-server
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8000
