apiVersion: v1
kind: Service
metadata:
  labels:
    app: ohad-airports-finder-server
  name: ohad-airports-finder-server
spec:
  type: LoadBalancer
  ports:
      - protocol: TCP
        port: 8000
        targetPort: 8000
  selector:
    app: ohad-airports-finder-server
status:
  loadBalancer: {}
