apiVersion: v1
kind: Service
metadata:
  labels:
    app: ohad-airports-finder-server-service
  name: ohad-airports-finder-server-service
spec:
  type: LoadBalancer
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
  selector:
    app: ohad-airports-finder-server-service
status:
  loadBalancer: {}
